# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_name', models.CharField(max_length=100)),
                ('bk_publick_YN', models.IntegerField()),
                ('bk_set_time', models.DateTimeField(auto_now=True)),
                ('bk_mf_time', models.DateTimeField(auto_now=True)),
                ('yn', models.IntegerField()),
                ('bk_content', models.CharField(max_length=200)),
                ('bk_sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob_name', models.CharField(max_length=100)),
                ('ob_set_time', models.DateTimeField(auto_now=True)),
                ('ob_mf_time', models.DateTimeField(auto_now=True)),
                ('yn', models.IntegerField()),
                ('ob_content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=100)),
                ('sp_set_time', models.DateTimeField(auto_now=True)),
                ('sp_mf_time', models.DateTimeField(auto_now=True)),
                ('yn', models.IntegerField()),
                ('sp_content', models.CharField(max_length=200)),
                ('sp_sequence', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UItest1.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('yn', models.IntegerField()),
                ('set_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UItest1.Tester'),
        ),
        migrations.AddField(
            model_name='object',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UItest1.Tester'),
        ),
        migrations.AddField(
            model_name='block',
            name='boject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UItest1.Object'),
        ),
        migrations.AddField(
            model_name='block',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UItest1.Tester'),
        ),
    ]
